deepspeed train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path lmsys/vicuna-13b-v1.5 \
    --version v1_sq \
    --data_path ./mixTraindata/llava_v1_5_mix665k.json \
    --image_folder ./mixTraindata \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter ./checkpoints/projector/sqllva-llava-13b-v1.7-pretrain-vlora-cluster/mm_projector.bin \
    --pretrain_lora  ./checkpoints/projector/sqllva-llava-13b-v1.7-pretrain-vlora-cluster/Vit-lora/adapter_model.bin \
    --mm_projector_type cluster \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-Sophon-v1.8-13b-vlora-665k-sq50-clu \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 6 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 2 \
    --learning_rate 2e-4 \
    --vision_tower_lr 2e-5 \
    --vit_lora_enable \
    --lora_alpha_vit 128 \
    --lora_r_vit 64 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to None \
    --data_aug False \
    --sq_r 0.5\
    